In [1]:
import pandas as pd
import numpy as np
from os import path,listdir

In [2]:
location = path.join('..','derivatives','trialwise','main_trial_level_cleaned.csv')
nback_subject = pd.read_csv(path.join('..','derivatives', 'subjectwise','nback_subject_level_8.23.2019.csv'))
procspeed_df = pd.read_csv(path.join('..','derivatives', 'finaldata','procspd_subject_level_8.23.2019.csv'))
sheet=pd.read_csv(location) #opening the excel file - trial level data
#sheet.head()
sheet.tail()

,Unnamed: 0,SubjNum,AgeGroup,ExperimenterName,RunNum,Date,Time,TrialNum,TrialNumbydomdist,Domain,...,StockNumber,BondNumber,GenderJudgment,TotalPayout,TrueProbGood,EstWithinRange?,val_estdiff_valid,absolute_error,val_error_3sd_removed,abs_error_3sd_removed
13531,13531,499,2,xw,12,08_08,56:53.4,2,14,GAIN,...,24,12,1,-24,0.155172,0,0.344828,0.344828,0.344828,0.344828
13532,13532,499,2,xw,12,08_08,56:53.4,3,15,GAIN,...,24,12,1,-14,0.300000,0,0.300000,0.300000,0.300000,0.300000
13533,13533,499,2,xw,12,08_08,56:53.4,4,16,GAIN,...,24,12,1,-8,0.500000,0,0.100000,0.100000,0.100000,0.100000
13534,13534,499,2,xw,12,08_08,56:53.4,5,17,GAIN,...,24,12,1,-6,0.300000,0,0.400000,0.400000,0.400000,0.400000
13535,13535,499,2,xw,12,08_08,56:53.4,6,18,GAIN,...,24,12,1,-4,0.155172,0,0.444828,0.444828,0.444828,0.444828

In [3]:
df = sheet.groupby(["SubjNum","StockValue"]).mean().reset_index()  #groupig things by subjnum and stock value
df.head()

,SubjNum,StockValue,Unnamed: 0,AgeGroup,RunNum,TrialNum,TrialNumbydomdist,FracST,FracRT,FaceST,...,StockNumber,BondNumber,GenderJudgment,TotalPayout,TrueProbGood,EstWithinRange?,val_estdiff_valid,absolute_error,val_error_3sd_removed,abs_error_3sd_removed
0,100,-10,38.333333,1.0,7.000000,3.333333,8.666667,2.142287e+06,4.634181,2.142293e+06,...,14.277778,10.333333,1.000000,19.555556,0.276485,0.111111,0.106848,0.143185,0.106848,0.143185
1,100,-2,30.666667,1.0,5.666667,3.666667,10.333333,2.142128e+06,3.434707,2.142132e+06,...,17.388889,14.333333,1.000000,-1.333333,0.669523,0.222222,-0.125079,0.152282,-0.125079,0.152282
2,100,2,32.333333,1.0,6.047619,3.047619,9.047619,2.142172e+06,2.375239,2.142176e+06,...,11.380952,7.714286,1.000000,9.142857,0.203618,0.095238,0.163049,0.186366,0.163049,0.186366
3,100,10,42.333333,1.0,7.533333,4.133333,10.133333,2.142368e+06,2.848761,2.142372e+06,...,12.466667,13.200000,1.000000,29.333333,0.515451,0.133333,0.017882,0.186715,0.017882,0.186715
4,101,-10,99.705882,1.0,5.235294,3.294118,9.647059,2.148198e+06,3.957810,2.148203e+06,...,11.647059,8.705882,0.941176,-19.529412,0.307429,0.588235,0.033747,0.040847,0.033747,0.040847

we made G10, G2, L10, L2 here:

In [4]:
four_errors = df.pivot(index='SubjNum',columns='StockValue',values='abs_error_3sd_removed') #pivot it into what we want: each subject has four prob. errors

In [5]:
mag_df = df = sheet.groupby(["SubjNum","Magnitude"]).mean().reset_index()  #groupig data by magnitude
mag_df.head()
mag_pivot = mag_df.pivot(index='SubjNum',columns='Magnitude',values='abs_error_3sd_removed') #pivot it into what we want: each subject has high and low magnitude

In [6]:
result1=sheet.groupby('SubjNum', as_index=False).mean().merge(four_errors, on='SubjNum') #create a sheet with 4 errors
result=result1.groupby('SubjNum', as_index=False).mean().merge(mag_pivot, on='SubjNum') #create a sheet with low/high magnitude
result.tail()

,SubjNum,Unnamed: 0,AgeGroup,RunNum,TrialNum,TrialNumbydomdist,FracST,FracRT,StockValue,FaceST,...,val_estdiff_valid,absolute_error,val_error_3sd_removed,abs_error_3sd_removed,-10,-2,2,10,high,low
183,495,13211.5,2.0,6.5,3.5,9.5,643526.139879,6.539036,0.444444,643533.840764,...,-0.022167,0.062997,-0.027408,0.058955,0.083899,0.058272,0.052847,0.045446,0.064490,0.053574
184,496,13283.5,2.0,6.5,3.5,9.5,22051.978362,8.625520,-0.222222,22061.750451,...,0.197211,0.322048,0.197211,0.322048,0.342134,0.259305,0.463141,0.208079,0.256010,0.386252
185,497,13355.5,2.0,6.5,3.5,9.5,183647.064669,4.192476,-0.444444,183652.396629,...,0.145791,0.312786,0.145791,0.312786,0.265821,0.266396,0.422590,0.260265,0.241707,0.383864
186,498,13427.5,2.0,6.5,3.5,9.5,190655.004094,4.637108,0.111111,190660.800153,...,0.018394,0.277675,0.018394,0.277675,0.268192,0.319909,0.354600,0.150935,0.227818,0.327531
187,499,13499.5,2.0,6.5,3.5,9.5,779000.249257,8.842838,0.000000,779010.230553,...,-0.007123,0.219470,-0.007123,0.219470,0.144043,0.298403,0.291763,0.125879,0.110922,0.328018

## Merge main task and nback data

In [7]:
result.rename(columns={'SubjNum': 'sub'}, inplace=True)
result.rename(columns={'high': 'HighMag'}, inplace=True)
result.rename(columns={'low': 'LowMag'}, inplace=True)
procspeed_df.rename(columns={'Subject': 'sub'}, inplace=True)
procspeed_df.rename(columns={'RT': 'procspeed'}, inplace=True)
main_task_nback = pd.merge(result, nback_subject, how='left', on="sub")
main_task_nback_procspeed = pd.merge(main_task_nback, procspeed_df, how='outer', on="sub")

In [8]:
output_path = path.join('..','derivatives','subjectwise','main_subject_level_abs_8.29.2019.csv')
main_task_nback_procspeed.to_csv(output_path)

In [9]:
#This is how you get a single row from a multi-index data frame:
#df.loc[(100,'GAIN')]