In [1]:
import pandas as pd
import numpy as np
from os import path,listdir

In [2]:
location = path.join('..','derivatives', 'trialwise','main_trial_level_cleaned.csv')
nback_subject = pd.read_csv(path.join('..','derivatives', 'subjectwise','nback_subject_level_8.23.2019.csv'))
procspeed_df = pd.read_csv(path.join('..','derivatives', 'finaldata','procspd_subject_level_8.23.2019.csv'))
sheet=pd.read_csv(location) #opening the excel file - trial level data
nback_subject.head()

,sub,RT,HIT%,FA%,CoR,study,RT_3sd_removed,CoR_3sd_removed
0,145,1619.714286,0.750000,0.153846,0.596154,1,1619.714286,0.596154
1,146,1401.740741,1.000000,0.230769,0.769231,1,1401.740741,0.769231
2,147,557.777778,0.333333,0.000000,0.333333,1,NaN,0.333333
3,148,710.333333,1.000000,0.074074,0.925926,1,710.333333,0.925926
4,149,819.962963,0.700000,0.100000,0.600000,1,819.962963,0.600000

In [3]:
df = sheet.groupby(["SubjNum","StockValue"]).mean().reset_index()  #groupig things by subjnum and stock value
df.head()

,SubjNum,StockValue,Unnamed: 0,AgeGroup,RunNum,TrialNum,TrialNumbydomdist,FracST,FracRT,FaceST,...,StockNumber,BondNumber,GenderJudgment,TotalPayout,TrueProbGood,EstWithinRange?,val_estdiff_valid,absolute_error,val_error_3sd_removed,abs_error_3sd_removed
0,100,-10,38.333333,1.0,7.000000,3.333333,8.666667,2.142287e+06,4.634181,2.142293e+06,...,14.277778,10.333333,1.000000,19.555556,0.276485,0.111111,0.106848,0.143185,0.106848,0.143185
1,100,-2,30.666667,1.0,5.666667,3.666667,10.333333,2.142128e+06,3.434707,2.142132e+06,...,17.388889,14.333333,1.000000,-1.333333,0.669523,0.222222,-0.125079,0.152282,-0.125079,0.152282
2,100,2,32.333333,1.0,6.047619,3.047619,9.047619,2.142172e+06,2.375239,2.142176e+06,...,11.380952,7.714286,1.000000,9.142857,0.203618,0.095238,0.163049,0.186366,0.163049,0.186366
3,100,10,42.333333,1.0,7.533333,4.133333,10.133333,2.142368e+06,2.848761,2.142372e+06,...,12.466667,13.200000,1.000000,29.333333,0.515451,0.133333,0.017882,0.186715,0.017882,0.186715
4,101,-10,99.705882,1.0,5.235294,3.294118,9.647059,2.148198e+06,3.957810,2.148203e+06,...,11.647059,8.705882,0.941176,-19.529412,0.307429,0.588235,0.033747,0.040847,0.033747,0.040847

we made G10, G2, L10, L2 here:

In [4]:
four_errors = df.pivot(index='SubjNum',columns='StockValue',values='val_error_3sd_removed') #pivot it into what we want: each subject has four prob. errors

In [5]:
mag_df = sheet.groupby(["SubjNum","Magnitude"]).mean().reset_index()  #groupig data by magnitude
mag_df.head()
mag_pivot = mag_df.pivot(index='SubjNum',columns='Magnitude',values='val_error_3sd_removed') #pivot it into what we want: each subject has high and low magnitude

In [6]:
domain_df = sheet.groupby(["SubjNum","Domain"]).mean().reset_index()  #groupig data by domain
domain_df.head()
domain_pivot = domain_df.pivot(index='SubjNum',columns='Domain',values='val_error_3sd_removed') #pivot it into what we want: each subject has high and low magnitude
domain_pivot
domain_df.head()

,SubjNum,Domain,Unnamed: 0,AgeGroup,RunNum,TrialNum,TrialNumbydomdist,FracST,FracRT,StockValue,...,StockNumber,BondNumber,GenderJudgment,TotalPayout,TrueProbGood,EstWithinRange?,val_estdiff_valid,absolute_error,val_error_3sd_removed,abs_error_3sd_removed
0,100,GAIN,36.5,1.0,6.666667,3.5,9.5,2.142254e+06,2.572539,5.333333,...,11.833333,10.000000,1.000000,17.555556,0.333548,0.111111,0.102563,0.186512,0.102563,0.186512
1,100,LOSS,34.5,1.0,6.333333,3.5,9.5,2.142208e+06,4.034444,-6.000000,...,15.833333,12.333333,1.000000,9.111111,0.473004,0.166667,-0.009115,0.147733,-0.009115,0.147733
2,101,GAIN,113.5,1.0,7.500000,3.5,9.5,2.148423e+06,2.208011,6.666667,...,13.166667,16.500000,1.000000,-15.555556,0.552187,0.555556,0.003091,0.050279,0.003091,0.050279
3,101,LOSS,101.5,1.0,5.500000,3.5,9.5,2.148230e+06,4.095154,-5.777778,...,10.833333,9.500000,0.944444,-26.666667,0.500000,0.500000,-0.031944,0.067169,-0.031944,0.067169
4,102,GAIN,188.5,1.0,8.000000,3.5,9.5,2.156017e+06,4.323398,5.333333,...,13.666667,12.666667,0.944444,-86.222222,0.420043,0.416667,0.034123,0.076142,0.034123,0.076142

In [7]:
result1=sheet.groupby('SubjNum', as_index=False).mean().merge(four_errors, on='SubjNum') #create a sheet with 4 errors
result2=result1.groupby('SubjNum', as_index=False).mean().merge(mag_pivot, on='SubjNum') #create a sheet with low/high magnitude
result3=result2.groupby('SubjNum', as_index=False).mean().merge(domain_pivot, on='SubjNum') #create a sheet with gain/loss domains
result3.head()

,SubjNum,Unnamed: 0,AgeGroup,RunNum,TrialNum,TrialNumbydomdist,FracST,FracRT,StockValue,FaceST,...,val_error_3sd_removed,abs_error_3sd_removed,-10,-2,2,10,high,low,GAIN,LOSS
0,100,35.5,1.0,6.5,3.5,9.5,2.142231e+06,3.303492,-0.333333,2.142235e+06,...,0.046724,0.167122,0.106848,-0.125079,0.163049,0.017882,0.059599,0.033849,0.102563,-0.009115
1,101,107.5,1.0,6.5,3.5,9.5,2.148327e+06,3.151583,0.444444,2.148331e+06,...,-0.014427,0.058724,0.033747,-0.090721,0.030021,-0.016145,-0.026528,-0.002326,0.003091,-0.031944
2,102,179.5,1.0,6.5,3.5,9.5,2.155802e+06,4.862018,-0.666667,2.155808e+06,...,0.012664,0.071852,0.022126,-0.056035,0.048234,0.014368,-0.017865,0.044988,0.034123,-0.010058
3,103,251.5,1.0,6.5,3.5,9.5,2.415893e+06,5.366772,0.000000,2.415900e+06,...,0.036173,0.184448,0.089934,-0.141148,0.214046,-0.018140,-0.015573,0.087919,0.097953,-0.025607
4,104,323.5,1.0,6.5,3.5,9.5,2.420087e+06,2.795020,0.111111,2.420091e+06,...,0.070082,0.252044,0.195984,-0.182242,0.248712,0.030023,0.146869,-0.006705,0.133293,0.006871

## Merge main task and nback and procspeed data

In [12]:
result3.rename(columns={'SubjNum': 'sub'}, inplace=True)
result3.rename(columns={'high': 'HighMag'}, inplace=True)
result3.rename(columns={'low': 'LowMag'}, inplace=True)
procspeed_df.rename(columns={'Subject': 'sub'}, inplace=True)
procspeed_df.rename(columns={'RT': 'procspeed'}, inplace=True)
result3['incongruence'] = result3['HighMag'] - result3['LowMag']
result3['domain_based_bias'] = result3['GAIN'] - result3['LOSS']
main_task_nback = pd.merge(result3, nback_subject, how='left', on="sub")
main_task_nback_procspeed = pd.merge(main_task_nback, procspeed_df, how='outer', on="sub")

In [13]:
derivs_dir = path.join('..','derivatives')
output_path = path.join(derivs_dir,'subjectwise',"main_subject_level_val_8.28.2019.csv")
main_task_nback_procspeed.to_csv(output_path) #this outputs in the code directory